# Generated by Django 3.2.12 on 2024-08-10 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_auctionlisting_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auctionlisting',
            name='image',
        ),
    ]
