# Generated by Django 3.2.12 on 2024-08-10 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_auto_20240810_1344'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionlisting',
            name='category',
            field=models.CharField(choices=[('ELEC', 'Electronics'), ('FASH', 'Fashion'), ('HOME', 'Home'), ('TOYS', 'Toys'), ('BOOK', 'Books')], default=1, max_length=4),
            preserve_default=False,
        ),
    ]
